// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ConsumeStartupFile() {
  return window['go']['main']['App']['ConsumeStartupFile']();
}

export function CopyImageAsset(arg1, arg2) {
  return window['go']['main']['App']['CopyImageAsset'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PushRecent(arg1) {
  return window['go']['main']['App']['PushRecent'](arg1);
}

export function ReadLocalAsset(arg1) {
  return window['go']['main']['App']['ReadLocalAsset'](arg1);
}

export function ResolveLocalPath(arg1, arg2) {
  return window['go']['main']['App']['ResolveLocalPath'](arg1, arg2);
}

export function SaveDialog(arg1) {
  return window['go']['main']['App']['SaveDialog'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
