// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {updater} from '../models';
import {config} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function CheckForUpdate(arg1:boolean):Promise<updater.CheckResult>;

export function CopyImageAsset(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function OpenDialog():Promise<string>;

export function OpenFile(arg1:string):Promise<main.FilePayload>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function PushRecent(arg1:string):Promise<config.Config>;

export function SaveDialog(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string,arg2:string):Promise<string>;

export function SetConfig(arg1:config.Config):Promise<void>;
