// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function ConsumeStartupFile():Promise<main.FilePayload>;

export function CopyImageAsset(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function OpenDialog():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<main.FilePayload>;

export function OpenPath(arg1:string):Promise<void>;

export function PushRecent(arg1:string):Promise<config.Config>;

export function ReadLocalAsset(arg1:string):Promise<string>;

export function ResolveLocalPath(arg1:string,arg2:string):Promise<main.LinkTarget>;

export function SaveDialog(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:number):Promise<number>;

export function SaveFileAs(arg1:string,arg2:string):Promise<string>;

export function SetConfig(arg1:config.Config):Promise<void>;
